import type { Metadata } from "next";

import ReduxProvider from "../components/redux-provider/redux-provider";

import "./globals.css";

import MainLayout from "@/components/main-layout/main-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col lg:flex-row">
        <ReduxProvider>
          <MainLayout>{children}</MainLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
