import type { Metadata } from "next";
import { Inter } from "next/font/google";

import ReduxProvider from "../components/redux-provider/redux-provider"; // Adjust the path as needed

import "./globals.css";
import NavigationBar from "@/components/nav-bar/nav-bar";
import SideBarMenu from "@/components/side-bar-menu/side-bar-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col lg:flex-row">
        <ReduxProvider>
          <div className="hidden lg:flex lg:w-1/6 lg:min-h-screen bg-gray-200">
            <div className="flex items-center justify-center h-full w-full">
              <p className="text-center">Ad Space (Left)</p>
            </div>
          </div>

          <main className="flex-grow bg-blue-200 h-screen w-screen">
            <SideBarMenu />
            <NavigationBar />
            {children}
          </main>

          <div className="hidden lg:flex lg:w-1/6 min-h-screen bg-red-500">
            <div className="flex items-center justify-center h-full w-full">
              <p className="text-center">Ad Space (Right)</p>
            </div>
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
